<!-- Über uns -->

<h1>Team</h1>

<table>
    <tbody>
        <tr>
            <th>Name</th>
            <th>Aufgabe</th>
        </tr>
        <tr>
            <td>Abiria</td>
            <td>Aktuar &amp; Staff</td>
        </tr>
        <tr>
            <td>AdP</td>
            <td>Kassier &amp; Küche</td>
        </tr>
        <tr>
            <td>Gurit</td>
            <td>Artemis &amp; Staff</td>
        </tr>
        <tr>
            <td>hori</td>
            <td>Präsident, Material &amp; Halle</td>
        </tr>
        <tr>
            <td>iVeal</td>
            <td>Staff</td>
        </tr>
        <tr>
            <td>little_hori</td>
            <td>Lounge &amp; Staff</td>
        </tr>
        <tr>
            <td>Noxis</td>
            <td>Staff</td>
        </tr>
        <tr>
            <td>Nymeria</td>
            <td>Staff</td>
        </tr>
        <tr>
            <td>RaV</td>
            <td>Netzwerk</td>
        </tr>
        <tr>
            <td>Rendrian</td>
            <td>Turniere</td>
        </tr>
        <tr>
            <td>Salt</td>
            <td>Tools &amp; Staff</td>
        </tr>
        <tr>
            <td>Shadow</td>
            <td>Vizepräsident, Support &amp; Web</td>
        </tr>
    </tbody>
</table>