<!-- Über uns -->

<h1>Team</h1>

<table>
    <tbody>
        <tr>
            <th>Name</th>
            <th>Aufgabe</th>
        </tr>
        <tr>
            <td>AdP</td>
            <td>Kassier &amp; Küche</td>
        </tr>
        <tr>
            <td>Boldar</td>
            <td>Staff</td>
        </tr>
        <tr>
            <td>Gurit</td>
            <td>Staff</td>
        </tr>
        <tr>
            <td>hori</td>
            <td>Material &amp; Halle</td>
        </tr>
        <tr>
            <td>iVeal</td>
            <td>Lounge</td>
        </tr>
        <tr>
            <td>little_hori</td>
            <td>Staff</td>
        </tr>
        <tr>
            <td>Noxis</td>
            <td>Staff</td>
        </tr>
        <tr>
            <td>Nymeria</td>
            <td>Aktuar & Staff</td>
        </tr>
        <tr>
            <td>ostnet</td>
            <td>Fotograf</td>
        </tr>
        <tr>
            <td>RaV</td>
            <td>Vizepräsident &amp; Netzwerk</td>
        </tr>
        <tr>
            <td>Rendrian</td>
            <td>Turniere</td>
        </tr>
        <tr>
            <td>sadi</td>
            <td>Präsident &amp; Tools</td>
        </tr>
        <tr>
            <td>Shadow</td>
            <td>Support &amp; Web</td>
        </tr>
        <tr>
            <td>zigi</td>
            <td>Entrance</td>
        </tr>
    </tbody>
</table>