<!-- Kontakt -->

<h1>LAN-Verein Berg "noprobLAN"</h1>

<h2>Präsident</h2>
<strong>Josua Schmid</strong>
v/o sadi
<br>
<em>Telefon:</em>
0788762432
<br>
<em>E-Mail:</em>
sadi [at] noproblan [dot] ch
<br>

<h2>Webmaster</h2>
<strong>Fabian Schweizer</strong>
v/o Shadow
<br>
<em>E-Mail:</em>
webmaster [at] noproblan [dot] ch
<br>

<h2>Haftungshinweis</h2>
Trotz sorgfältiger inhaltlicher Kontrolle übernehmen wir keine Haftung
fur die Inhalte externer Links. Für den Inhalt der verlinkten Seiten
sind ausschließlich deren Betreiber verantwortlich.
