<!-- Kontakt -->

<h1>LAN-Verein Berg "noprobLAN"</h1>

<h2>Präsident</h2>
<strong>Jürg Horisberger</strong>
v/o Hori
<br>
<em>Telefon:</em>
0774334464
<br>
<em>E-Mail:</em>
hori [at] noproblan [dot] ch
<br>

<h2>Webmaster</h2>
<strong>Fabian Schweizer</strong>
v/o Shadow
<br>
<em>E-Mail:</em>
webmaster [at] noproblan [dot] ch
<br>

<h2>Haftungshinweis</h2>
Trotz sorgfältiger inhaltlicher Kontrolle übernehmen wir keine Haftung
für die Inhalte externer Links. Für den Inhalt der verlinkten Seiten
sind ausschließlich deren Betreiber verantwortlich.
