<div id="view-content">
    <div id="messages"></div>

    <h2>Fast ausverkauft!</h2>
    <p>
        Schon sehr bald öffnen wir die Türen für die noprobLAN v47.1. Willst
        auch Du kommen, hast Du dir Deinen Platz aber noch nicht gesichert?
        Dann nichts wie ran an deinen PC und sichere dir noch heute einen der
        letzten freien Plätze.<br /> <br /> Wir freuen uns euch schon bald
        begrüssen zu dürfen.<br /> Das NPL-Team
    </p>

    <hr />

    <h2>noprobLAN v43.2 ping is to high!</h2>
    <p>
        <strong>Es dankt das NOC allen Netzwerk-Betatestern ;)</strong><br />
        <br /> Die noprobLAN v43.2 ist vorbei. Das npL-Team befindet sich im
        Sommerschlaf (träumt von den Bildern in der Gallerie) und bereitet
        sich geistig auf die nächste LAN am 10.10.2014 vor.<br /> <br /> Es
        grüsst das NOC und das ganze npL-Team
    </p>

    <hr />

    <h2>npL v43.2 AUSVERKAUFT</h2>
    <p>
        Zwei Monate vor der LAN sind wir bereits komplett ausverkauft!<br /> <br />
        <strong>ABER</strong> für alle, die nicht vorausbezahlt haben gibt es
        noch eine Chance!<br /> Ein paar wenige weitere Plätze können wir
        zusätzlich einrichten und Du hast die Chance einen dieser Plätze zu
        ergattern.<br /> Interessiert? Dann schick uns ein originelles Mail
        warum ausgerechnet Du einen dieser Plätze haben sollst bis am
        05.04.2014 um 23:59 Uhr an special@npl.ch und mit etwas Glück kannst
        Du doch noch an die LAN kommen.<br /> Ihr seid eine kleine Gruppe?
        Dann schreibt ein Mail für die Gruppe! Bitte gebt dann auch die Anzahl
        Leute an.<br /> Also ran an die Tastatur!<br /> <br /> Das npL-Team
    </p>

    <hr />

    <h2>Noch drei Monate...</h2>
    <p>
        ...und dann ist es wieder soweit. Die nächste noprobLAN schaltet ihre
        Ports frei und öffnet euch den Weg ins Netwerk.<br /> Bereits sind
        über die Hälfte der Plätze belegt.<br /> Also melde dich noch heute an
        und vergiss die Vorauszahlung nicht, um dir Deinen Platz zu sichern.<br />
        <br /> Wir freuen uns schon jetzt, euch wieder in der MZH Berg zu
        begrüssen.
    </p>

    <hr />

    <h2>Frohe Festtage</h2>
    <p>
        Es ist wieder soweit und ein weiteres Jahr geht dem Ende zu.<br /> Uns
        bleibt nur noch euch und euren Familien ein schönes Weihnachtsfest und
        einen guten Rutsch ins neue Jahr zu wünschen.<br /> Wir freuen uns
        euch auch im Jahr 2014 wieder die gemütlichste LAN-Party zu bieten und
        hoffen auf eine rege Teilnahme.<br /> <br /> Das npL-Team
    </p>

    <hr />

    <h2>noprobLAN v39.1 has ended</h2>
    <p>
        <strong>Ein Dankeschön aus der Küche</strong><br /> Am letzten Sonntag
        schlossen sich die Türen der noprobLAN ein weiteres Mal.<br /> Wir
        dürfen gemeinsam auf ein gemütliches und gelungenes Wochenende
        zurückschauen.<br /> Dies verdanken wir vor allem den Gamerinnen und
        Gamern aus dem In- und Ausland, welche zur guten Atmosphäre
        beigetragen haben.<br /> Ein grosses Dankeschön an alle, die da waren.
        Ohne euch ist die noprobLAN keine noprobLAN!<br /> <br /> Wir freuen
        uns schon jetzt darauf die Türen am 30.05.2014 ab 12:00 Uhr (!) wieder
        für euch zu öffnen.<br /> Und ich für meinen Teil freue mich bereits
        wieder euch einen kulinarischen Leckerbissen aufzutischen.<br /> <br />
        Es grüsst AdP, der Küchenchef, und der Rest eures npL-Teams
    </p>

    <hr />

    <h2>Fully loaded</h2>
    <p>
        <strong>Wir sind ausverkauft!</strong><br /> Sitzplätze gibt es nur
        noch auf dem Schwarzmarkt oder durch Bestechung des Teams ;-)<br /> <br />
        Nie hätten wir gedacht, dass wir so überrannt werden.<br /> Wir freuen
        uns wahnsinnig auf die LAN und die gemütliche Stimmung mit euch allen.<br />
        Gleichzeitig ist es natürlich schade, dass nicht alle kommen können.<br />
        Bei einem solchen Ansturm müssen wir für die Zukunft natürlich
        weiterdenken.<br /> Wie das sein wird, wissen wir noch nicht.<br /> <br />
        Auf jeden Fall möchten wir euch allen herzlichst danken.<br /> Wir
        haben klein angefangen und nur mit euch konnten wir wachsen.<br /> Nur
        mit euch ist die noprobLAN die gemütlichste LAN-Party der Schweiz!<br />
        <br /> Das npL-Team
    </p>

    <hr />

    <h2>Heisser Sommer, gemütlicher Herbst</h2>
    <p>
        <strong>Sitzplatz, Vorauszahlung, Platzknappheit.</strong><br /> Wie
        es aussieht haben wir wiederum mehr Anmeldungen als Plätze!<br /> In
        diesem Falle gilt: Die ersten 120, die vorauszahlen, erhalten die
        Plätze.<br /> Du bist noch garnicht angemeldet?<br /> Dann pack die
        Gelegenheit am Schopf, melde dich an und zahle direkt voraus.<br />
        Die Chancen sind jetzt noch da einen der Sitzplätze zu ergattern! <br />
        <br /> <strong>Abkühlung, Ferien, Gemeinsamkeit.</strong><br /> Ein
        heisser Sommer haben wir diese Tage.<br /> Aber keine Bange, auf
        diesen heissen Sommer folgt ein gemütlicher Event ;)<br /> Einige von
        euch verbrachten die Sommerferien im Ausland,<br /> andere gönnten
        sich einen Sprung ins kühle Nass.<br /> Wir sind in den Vorbereitungen
        für die nächste noprobLAN diesen Oktober.<br /> Oh, natürlich gönnen
        auch wir uns Abkühlung ;) <br />
        <br /> Das npL-Team
    </p>

    <hr />

    <h2>Wir sind fast voll...</h2>
    <p>
        <strong>Wer zuerst kommt, mahlt zuerst</strong><br /> Unsere Plätze
        sind begrenzt.<br /> Wir haben leider nicht die Möglichkeit mehr als
        120 Leute unterzubringen. <br />
        <br /> So wie es jetzt aussieht bekommen nur diejenigen einen
        Sitzplatz, die vorausbezahlt haben.<br /> Darum bitten wir Dich so
        schnell wie möglich einzuzahlen!<br /> <br /> <b
            style="color: darkred;">...er Vorfreude</b><br /> <br /> Das npL-Team
    </p>

    <hr />

    <h2>The number eleven</h2>
    <p>
        <strong>Incoming noprobLAN v35.6</strong><br /> In etwa zwei Monaten
        ist es soweit, die noprobLAN v35.6 wird ihre Tore öffnen.<br /> <br />
        Wir hoffen wie immer auf ein gemütliches Beisammensein!<br />
        <br /> <a class="button"
            href="<?= $this->baseUrl('lan/info/lanid/11') ?>">Zur LAN</a><br />
    </p>

    <hr />

    <h2>noprobLAN participate @ GameThat</h2>
    <p>
        <strong>We will be there</strong><br /> Mitte Februar findet in Flawil
        die GameThat statt.<br /> Wir haben uns mit dem OK-Mitglied
        ill.oOminated unterhalten und haben uns bereit erklärt, der GameThat
        unser Material zur Verfügung zu stellen.<br /> Im Gegenzug werden
        OK-Mitglieder der noprobLAN an der GameThat anwesend sein.<br /> Wir
        hoffen bekannte Gesichter zu sehen, Herausforderungen zu meistern und
        freuen uns auf die GameThat!
    </p>

    <hr />

    <h2>21.12.2012</h2>
    <p>
        <strong>Apocalypse hat verschlafen</strong><br /> Nun, das mit dem
        Weltuntergang scheint wohl schief gegangen zu sein...<br /> Umso mehr
        freuen wir uns euch die nächsten noprobLANs anzukünden!<br /> <br /> <strong>noprobLAN
            v35.6</strong> 5. - 7.April 2013<br /> <strong>noprobLAN v39.1</strong>
        11. - 13. Oktober 2013
    </p>

    <hr />

</div>
