<?php
/* @var $lan Application_Model_Lan */
$lan = $this->lan;
$infos = $this->infos;
$hasTicket = $this->hasTicket;
$hasPaid = $this->hasPaid;
$userTickets = $this->userTickets;
if (is_null($lan->getRegistrationEndDateTime())) {
    $registrationPossible = true;
} else {
    $regEndDateTime = new DateTime($lan->getRegistrationEndDateTime());
    if ($regEndDateTime > new DateTime()) {
        $registrationPossible = true;
    } else {
        $registrationPossible = false;
    }
}
?>
<div id="view-content">
    <?php

if ($lan != null) {
    $participants = $this->participants;
    ?>
    <div id="title">
        <h1>Informationen <?= $this->escape($lan->getName()) ?></h1>
    </div>
    <div id="lans">
        <hr />
        <p id="participate">
            <?php
    
echo $this->partial('partials/lan/buttons.phtml', 
            array(
                    'lanId' => $lan->getId(),
                    'hasPaid' => $hasPaid,
                    'hasTicket' => $hasTicket,
                    'registrationPossible' => $registrationPossible
            ));
    ?>
        </p>
        <div id="infos">
            <?php if ($infos != null) { ?>
                <?php foreach ($infos as $info) { ?>
            <hr />
            <h3><?php echo $this->escape($info->getName()) ?></h3>
            <p class="lan-info"><?php echo $info->getInfo() ?></p>
                <?php } ?>
            <?php } else { ?>
            <p>Keine Informationen vorhanden</p>
            <?php } ?>
        </div>
        <hr />
        <h2>Teilnehmer</h2>
        <div class="participants">
            <p>
        <?php
    if (empty($participants)) {
        ?>
                Noch keine Teilnehmer!
                <?php if (true === $registrationPossible) : ?><a class="button"
                    href="<?php echo $this->url(array('controller'=>'lan','action'=>'participate','lanid'=>$lan->getId(),'participate'=>'yes','prevcont'=>'lan'),'default',true) ?>">Ich
                    bin der Erste!</a>
                <?php endif; ?>
        <?php
    } else {
        $links = array();
        foreach ($participants as $participant) {
            $link = '<a href="' . $this->url(
                    array(
                            "controller" => "user",
                            "action" => "profile",
                            "id" => $participant['id']
                    ), "default", true) . '">
                            ' .
                     $this->escape($participant['user']) . '</a>';
            $links[] = $link;
        }
        echo implode(", ", $links);
    }
    ?>
            </p>
        </div>
    </div>
    <?php } else { ?>
    <div id="title">
        <h1>LAN Informationen</h1>
    </div>
    <?php } ?>
</div>