<?php
/* @var $lan Application_Model_Lan */
$lan = $this->lan;
$infos = $this->infos;
$hasTicket = $this->hasTicket;
$hasPaid = $this->hasPaid;
$userTickets = $this->userTickets;
if (is_null($lan->getRegistrationEndDateTime())) {
    $registrationPossible = true;
} else {
    $regEndDateTime = new DateTime($lan->getRegistrationEndDateTime());
    if ($regEndDateTime > new DateTime()) {
        $registrationPossible = true;
    } else {
        $registrationPossible = false;
    }
}
?>
<div id="view-content">
    <?php

    if ($lan != null) {
        $participants = $this->participants;
        ?>
        <div id="title">
            <h1>Informationen <?= $this->escape($lan->getName()) ?></h1>
        </div>
        <div id="lans">
            <hr/>
            <p id="participate">
                <?php

                echo $this->partial('partials/lan/buttons.phtml',
                    array(
                        'lanId' => $lan->getId(),
                        'hasPaid' => $hasPaid,
                        'hasTicket' => $hasTicket,
                        'registrationPossible' => $registrationPossible
                    ));

                if (!$hasPaid && $registrationPossible && $hasTicket) {
                    $accountUrl = $this->url(array('controller'=>'user','action'=>'account'),'default',true);
                    ?><a class="button" href="<?php echo $accountUrl ?>">Anmeldung konfigurieren</a><?php
                }
                ?>

            </p>
            <?php echo $this->partial('lan/partials/infos.phtml',
                array(
                    'infos' => $infos
                )); ?>

            <?php echo $this->partial('lan/partials/participants.phtml',
                array(
                    'participants' => $participants,
                    'registrationPossible' => $registrationPossible,
                    'lan' => $lan
                )); ?>
        </div>
    <?php } else { ?>
        <div id="title">
            <h1>LAN Informationen</h1>
        </div>
    <?php } ?>
</div>
