<?php
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();

if ($this->hasPaid == true):
  $url = $this->url(array('controller'=>'lan','action'=>'reservation','lanid'=>$this->lanId),'default',true);
  ?><a class="button" href="<?php echo $url ?>">Zur Sitzplatzreservation</a><?php
else:
  if ($this->registrationPossible == true) {
    if ($this->hasTicket == true) {
      $url = $this->url(array('controller'=>'lan','action'=>'participate','lanid'=>$this->lanId,'participate'=>'no','prevcont'=>$controller),'default',true);
      ?><a class="button" href="<?php echo $url ?>">Von der LAN abmelden</a><?php
    } else {
      $url = $this->url(array('controller'=>'lan','action'=>'participate','lanid'=>$this->lanId,'participate'=>'yes','prevcont'=>$controller),'default',true);
      ?><a class="button" href="<?php echo $url ?>">An der LAN teilnehmen</a><?php
    }
  } else {
    ?>Anmeldung geschlossen<?php
  }
endif;
?>

