<?php
foreach ($this->lans as $attendingLan) {
    if ($attendingLan['attending'] && $attendingLan['registration_possible']) {
        foreach ($this->tickets as $ticket) {
            /* @var $ticket Application_Model_Ticket */
            if ($ticket->getLanId() == $attendingLan['id']) {
                $status = $ticket->getStatus();
                $lanId = $ticket->getLanId();
                $userId = $ticket->getUserId();
                $mapperLans = new Application_Model_Mapper_LansMapper();
                $mapperUsers = new Application_Model_Mapper_UsersMapper();
                $lan = new Application_Model_Lan();
                $user = new Application_Model_User();
                $price = 60;
                if ($status == Application_Model_Ticket::STATUS_NOTPAID) {
                    $mapperLans->find($lanId, $lan);
                    $mapperUsers->find($userId, $user);
                    $lanname = $lan->getName();
                    $lanname = str_replace(" ", "_", $lanname);
                    $username = $user->getUsername();
                    $extras = $ticket->getExtrasSplitted();
//                    $extras['helping'] = $ticket->getHelping();
                    $form = new Application_Form_TicketExtras();
                    foreach ($extras as $key => $value) {
                        $element = $form->getElement($key);
                        if ($value == true) {
                            switch ($key) {
                                case 'breakfast':
                                    $price += 5;
                                    break;
                                case 'dinner':
                                    $price += 15;
                                    break;
                                case 'cable':
                                    $price += 10;
                                    break;
                            }
                            $element->setAttrib("checked", "checked");
                        } else {
                            $element->setAttrib("checked", "");
                        }
                    }
                    $form->getElement('ticketId')->setValue($ticket->getId());
                    $form->setAction(
                            $this->url(
                                    array(
                                            'controller' => 'ticket',
                                            'action' => 'changeextras',
                                            'ticketid' => $ticket->getId()
                                    ), 'default', true));
                    ?>
<hr />
<h3>Vorauszahlung (<?= $lan->getName() ?>)</h3>
<b>Vorgehen</b>
<ol>
    <li>Direkt via QR Rechnung bezahlen oder mittels untenstehenden Angaben vorauszahlen</li>
    <li>Auf Bestätigung warten</li>
</ol>
<br />
<b>Einzahlung</b>
<br />
<br />
                    <table>
                        <tr>
                            <th>IBAN</th>
                            <td>CH08 8080 8004 9238 7040 7</td>
                        </tr>
                        <tr>
                            <th>Empfänger</th>
                            <td>noprobLAN<br />Löwenstrasse 1<br />8585 Birwinken</td>
                        </tr>
                        <tr>
                            <th>Konto-Nr</th>
                            <td>85-1858-3</td>
                        </tr>
                        <tr>
                            <th>Preis</th>
                            <td><?php echo $price ?></td>
                        </tr>
                        <tr>
                            <th>Zahlungszweck</th>
                            <td><?php echo $lanname ?><br />ID <?php echo $ticket->getId() ?></td>
                        </tr>
                    </table>
                    <br />
                    <a class="button" target="_blank" href="<?php echo $this->url(array('controller'=>'ticket','action'=>'showpayment'),'default',true) ?>?event=<?= $lanname ?>&id=ID%20<?= $ticket->getId() ?>&amount=<?= $price ?>">
                        <img src="<?php echo $this->baseUrl('img/pdf.png') ?>" width="16px" alt="PDF Icon" />
                        QR Rechnung
                    </a>
<?php
                }
            }
        }
    }
}
