<?php
foreach ($this->lans as $attendingLan) {
    if ($attendingLan['attending'] && $attendingLan['registration_possible']) {
        foreach ($this->tickets as $ticket) {
            /* @var $ticket Application_Model_Ticket */
            if ($ticket->getLanId() == $attendingLan['id']) {
                $status = $ticket->getStatus();
                $lanId = $ticket->getLanId();
                $userId = $ticket->getUserId();
                $mapperLans = new Application_Model_Mapper_LansMapper();
                $mapperUsers = new Application_Model_Mapper_UsersMapper();
                $lan = new Application_Model_Lan();
                $user = new Application_Model_User();
                $price = 40;
                if ($status == Application_Model_Ticket::STATUS_NOTPAID) {
                    $mapperLans->find($lanId, $lan);
                    $mapperUsers->find($userId, $user);
                    $lanname = $lan->getName();
                    $lanname = str_replace(" ", "_", $lanname);
                    $username = $user->getUsername();
                    $extras = $ticket->getExtrasSplitted();
                    $extras['helping'] = $ticket->getHelping();
                    $form = new Application_Form_TicketExtras();
                    foreach ($extras as $key => $value) {
                        $element = $form->getElement($key);
                        if ($value == true) {
                            switch ($key) {
                                case 'breakfast':
                                    $price += 5;
                                    break;
                                case 'dinner':
                                    $price += 15;
                                    break;
                                case 'cable':
                                    $price += 10;
                                    break;
                            }
                            $element->setAttrib("checked", "checked");
                        } else {
                            $element->setAttrib("checked", "");
                        }
                    }
                    $form->getElement('ticketId')->setValue($ticket->getId());
                    $form->setAction(
                            $this->url(
                                    array(
                                            'controller' => 'ticket',
                                            'action' => 'changeextras',
                                            'ticketid' => $ticket->getId()
                                    ), 'default', true));
                    ?>
<hr />
<h3>Vorauszahlung (<?= $lan->getName() ?>)</h3>
<b>Vorteile beim Vorauszahlen:</b>
<ul>
    <li>Ermässigter Eintritt (40 CHF&sup1;)</li>
    <li>Nachstehende Optionen vergünstigt (Preis jeweils in Klammern)</li>
    <li>Sitzplatz garantiert</li>
    <li>Sitzplatzreservation&sup2;</li>
</ul>
<b>Vorgehen</b>
<ol>
    <li>Optionen wählen</li>
    <li>Speichern</li>
    <li>Einzahlungsschein nach untenstehender Vorlage ausfüllen (eBanking
        oder bei der Post)</li>
    <li>Bezahlen und auf Bestätigung warten</li>
    <li>Sitzplatz reservieren&sup2;</li>
</ol>
                    <b>Helfer</b>
                    <ul>
                        <li>Gib bei den Optionen an, dass du helfen möchtest. Wir sind froh um helfende Hände :-)</li>
                        <li>Du wirst dann von uns kontaktiert</li>
                        <li>Grundsätzlich kannst du beim Auf- oder Abbau oder während der LAN helfen</li>
                        <li>Je nach Anzahl der Schichten erhälst du Vergünstigungen (Gratis Eintritt, Gratis Essen, ...)</li>
                    </ul>
<small>&sup1; Vorauszahlung gilt auch für weibliche Gamer (wird an der
    LAN zurückerstattet).</small>
<br />
<small>&sup2; Sobald/sofern verfügbar.</small>
<br />
<br />
<b>Optionen</b>
<br />
<br />
<?= $form ?>
<br />
<b>Einzahlungsschein</b>
<br />
<small>Hast du auch wirklich gespeichert?</small>
<br />
<br />
<a id="ezTarget"
    href="<?php echo $this->url(array('controller'=>'ticket','action'=>'showpayment'),'default',true) ?>?event=<?= $lanname ?>&id=ID%20<?= $ticket->getId() ?>&amount=<?= $price ?>"
    target="_blank" class="ezs"> <img id="ezPic"
    src="<?php echo $this->url(array('controller'=>'ticket','action'=>'showpayment'),'default',true) ?>?event=<?= $lanname ?>&id=ID%20<?= $ticket->getId() ?>&amount=<?= $price ?>"
    alt="Einzahlungsschein" width="400px" />
</a><br /><br />
                    <table>
                        <tr>
                            <th>IBAN</th>
                            <td>CH87 8137 9000 0025 7424 4</td>
                        </tr>
                        <tr>
                            <th>Empfänger</th>
                            <td>noprobLAN<br />Löwenstrasse 1<br />8585 Birwinken</td>
                        </tr>
                        <tr>
                            <th>Konto-Nr</th>
                            <td>85-1858-3</td>
                        </tr>
                        <tr>
                            <th>Preis</th>
                            <td><?php echo $price ?></td>
                        </tr>
                        <tr>
                            <th>Zahlungszweck</th>
                            <td><?php echo $lanname ?><br />ID <?php echo $ticket->getId() ?></td>
                        </tr>
                    </table>
<?php
                }
            }
        }
    }
}
